# Use postgres/example user/password credentials
version: '3.1'

services:
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=example
    image: mongo:4
    restart: always
    # volumes:
    #   - ~/mongo/data/db:/data/db
    ports:
      - 27019:27017
